### ISSUE TITLE
Register in Linguist database

### ISSUE THREAD

**Issue by kvark** [ron-rs/ron#85]
Current view of a RON file in Github is rather [unusable](https://github.com/redox-os/orbgame/blob/master/examples/adventure/game.ron). Github uses [Linguist](https://github.com/github/linguist) for determining the syntax and applying the correct highlight. We should make an upstream feature to recognize RON.

**Comment by moosingin3space** [comment]
Linguist will require a TextMate-compatible grammar for RON. I gave this a look earlier today.

**Comment by pyfisch** [comment]
I am not sure if RON is already popular enough:

> In most cases we prefer that extensions be in use in hundreds of repositories before supporting them in Linguist.

https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-an-extension-to-a-language

**Comment by CAD97** [comment]
I found the "culprit", at least: https://github.com/github/linguist/blob/14a7cb2d1b3d6f822701bccf36666303509c7621/lib/linguist/languages.yml#L2646-L2665

```yml
Markdown:
  type: prose
  aliases:
  - pandoc
  ace_mode: markdown
  codemirror_mode: gfm
  codemirror_mime_type: text/x-gfm
  wrap: true
  extensions:
  - ".md"
  - ".markdown"
  - ".mdown"
  - ".mdwn"
  - ".mkd"
  - ".mkdn"
  - ".mkdown"
  - ".ron"
  - ".workbook"
  tm_scope: source.gfm
  language_id: 222
```

GitHub's preview seems hardwired to render `*.ron` as markdown: [no matter how hard I try to tell Linguist otherwise](https://github.com/CAD97/ron-display/blob/master/.gitattributes).

Notably, [using a file extension that isn't on that list](https://github.com/CAD97/ron-display/blob/master/demo.rson) makes it render in a monospace font (without any syntax highlighting).

I'm pretty sure the fact that you can't opt-out of the markdown presentation is a bug, or at least a valid feature request, so [I'm going to open an issue on the linguist repository].

For getting into Linguist: [`extension:ron NOT <data>`](https://github.com/search?utf8=%E2%9C%93&q=extension%3Aron+NOT+%3Cdata%3E&type=Code): 252 code results, sorting through false positives right now. Actually, I think the classification of `.ron` as markdown is in error, and should be referring to [`.ronn`](https://github.com/rtomayko/ronn) instead.
